/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ui;

import com.vrf.UserInputVerifier;
import com.dao.ComboUser;
import com.dao.FinalTransaction;
import com.domain.Transaction;
import com.domain.User;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Tural
 */
public class LivingPlanUi extends javax.swing.JFrame {

    /**
     * Creates new form LivingPlanUi
     */
    public LivingPlanUi() {
        initComponents();
        fillUserComboBox(new ComboUser().getUsers());
        fillUserJList(new ComboUser().getUsers());
        
        SimpleDateFormat sf = new SimpleDateFormat("YYYY-MM-dd");
        dateTextField.setText(sf.format(new Date()));
        

    }

    private void fillUserComboBox(ArrayList<User> ul) {
        userCombo.removeAllItems();
        for (User u : ul) {
            userCombo.addItem(u.getUserName());
        }
    }

    private void fillUserJList(ArrayList<User> ul) {

        DefaultListModel dl = new DefaultListModel();
        dl.removeAllElements();
        for (User u : ul) {
            dl.addElement(u.getUserName());
        }
        userListJList.setModel(dl);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        userCombo = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userListJList = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        paidAmountTxtField = new javax.swing.JTextField();
        addTransaction = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        descriptionTxtArea = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        dateTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        showDebt = new javax.swing.JButton();
        showTransaction = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Paid by");

        userCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        userCombo.setName("userCombo"); // NOI18N
        userCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userComboActionPerformed(evt);
            }
        });

        jLabel2.setText("Related to");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        userListJList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(userListJList);

        jLabel3.setText("Amount");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel3.setName(""); // NOI18N

        paidAmountTxtField.setName(""); // NOI18N
        paidAmountTxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                paidAmountTxtFieldKeyPressed(evt);
            }
        });

        addTransaction.setText("Add");
        addTransaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTransactionActionPerformed(evt);
            }
        });

        jLabel4.setText("Description");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        descriptionTxtArea.setColumns(20);
        descriptionTxtArea.setRows(5);
        jScrollPane2.setViewportView(descriptionTxtArea);

        jLabel5.setFont(new java.awt.Font("Ubuntu", 2, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(22, 8, 11));
        jLabel5.setText("Click \"Ctrl\" for multiselection");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel5.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        jLabel5.setEnabled(false);
        jLabel5.setFocusable(false);
        jLabel5.setIconTextGap(2);
        jLabel5.setMaximumSize(new java.awt.Dimension(50, 10));
        jLabel5.setMinimumSize(new java.awt.Dimension(50, 10));
        jLabel5.setPreferredSize(new java.awt.Dimension(75, 10));

        jLabel6.setText("Date");

        jLabel7.setFont(new java.awt.Font("Ubuntu", 2, 10)); // NOI18N
        jLabel7.setText("*date format is 'YYY-MM-DD'");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(75, 75, 75))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addTransaction, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dateTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                    .addComponent(paidAmountTxtField)
                    .addComponent(jScrollPane1)
                    .addComponent(userCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(userCombo)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paidAmountTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(24, 24, 24)
                .addComponent(addTransaction))
        );

        showDebt.setText("Other Details");
        showDebt.setPreferredSize(new java.awt.Dimension(171, 23));
        showDebt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showDebtActionPerformed(evt);
            }
        });

        showTransaction.setText("Daily transaction result");
        showTransaction.setPreferredSize(new java.awt.Dimension(171, 23));
        showTransaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showTransactionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(showTransaction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(showDebt, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showDebt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showTransaction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addTransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTransactionActionPerformed

        FinalTransaction ft = new FinalTransaction();
        UserInputVerifier verifier = new UserInputVerifier();
        //checking if user enters numeric value for actual amount

        if (!verifier.verify(paidAmountTxtField)) {
            JOptionPane.showMessageDialog(this, "Enter Number to \"Paid amount\" field");
            return;
        }
        Double paidAmount = Double.parseDouble(paidAmountTxtField.getText());
        //
        //checking if user selected ack by user
        ArrayList ackByUsers = null;

        if (userListJList.getSelectedValuesList().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Select ackuired by users!!");
            return;

        }
        ackByUsers = (ArrayList) userListJList.getSelectedValuesList();

        String description = descriptionTxtArea.getText();
        int paidByUserId = ft.getUserIdByUserName((String) userCombo.getSelectedItem());
        User paidByUser = new User(paidByUserId);
        ArrayList<User> ackByUserList = new ArrayList<User>();

        try {
            for (Object o : ackByUsers) {
                User u = new User(ft.getUserIdByUserName((String) o));
                ackByUserList.add(u);
            }
        } catch (NullPointerException e) {
            e.printStackTrace();
        }

        //adding to DB
        boolean isAdded = false;

        if (JOptionPane.showConfirmDialog(this, "Are you sure to add?") == JOptionPane.YES_OPTION) {
            try {
                isAdded = ft.addTrToDB(paidByUser, ackByUserList, description, paidAmount, dateTextField.getText());
            } catch (Exception ex) {
                Logger.getLogger(LivingPlanUi.class.getName()).log(Level.SEVERE, null, ex);
                ex.printStackTrace();
                JOptionPane.showMessageDialog(userCombo, "Wrong date format");
            }
            JOptionPane.showMessageDialog(this, "Transaction is added successfully!");
        } else {
            return;
        }

        if (!isAdded) {
            JOptionPane.showMessageDialog(this, "Transaction is not added due to unknown error!");
        }


    }//GEN-LAST:event_addTransactionActionPerformed

    private void showTransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showTransactionActionPerformed
        new Result().setVisible(true);

    }//GEN-LAST:event_showTransactionActionPerformed

    private void userComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userComboActionPerformed

    private void showDebtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showDebtActionPerformed
        new DebtUI().setVisible(true);

    }//GEN-LAST:event_showDebtActionPerformed

    private void paidAmountTxtFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_paidAmountTxtFieldKeyPressed
        
    }//GEN-LAST:event_paidAmountTxtFieldKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LivingPlanUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LivingPlanUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LivingPlanUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LivingPlanUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LivingPlanUi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addTransaction;
    private javax.swing.JTextField dateTextField;
    private javax.swing.JTextArea descriptionTxtArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField paidAmountTxtField;
    private javax.swing.JButton showDebt;
    private javax.swing.JButton showTransaction;
    private javax.swing.JComboBox userCombo;
    private javax.swing.JList userListJList;
    // End of variables declaration//GEN-END:variables
}
